#!/bin/bash




carpetas=(
BabyandTeddy
BabyFaces
Catmoji
CoolPanda
Cowmoji2
download
Easter1
EidulFitr
EnglishChat3
FunnyChicken
Girlmoji
Leo
Marshmallow
MiloThePug
Oinker
PikkaPengu
VegetableEmoji2)


echo -e  '\n{
		  "android_play_store_link": "",
		  "ios_app_store_link": "",
		  "version":1,
		  "sticker_packs": 
		  [\n'

for identifier in ${carpetas[*]}
do
	temp=$(ls ./$identifier)
	imageTry=${temp[1]}

	echo	-e '\n{
				"identifier": "'$identifier'",
				"name": "'$identifier'",
				"publisher": "meh",
				"tray_image_file": "'$imageTry'",
				"image_data_version":"1",
				"avoid_cache":false,
				"publisher_email":"",
				"publisher_website": "",
				"privacy_policy_website": "",
				"license_agreement_website": "",
				"stickers": [\n'

	for file in ${temp[*]}
	do

		echo -e '\n{
					 "image_file": "'$file'",
					 "emojis": ["☕","🙂"]
				  },\n'
	done
			echo -e   "\n]\n"
			echo -e '\n}\n'

done
		  echo -e '\n]\n'
		echo -e '\n}\n'





